# This is a basic workflow to help you get started with Actions

name: main

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  wine-build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: build
        run: |
          brew install --formula bison mingw-w64 pkgconfig
          brew install --formula freetype gnutls molten-vk sdl2
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20240606/llvm-mingw-20240606-ucrt-macos-universal.tar.xz
          tar -Jxvf llvm-mingw-20240606-ucrt-macos-universal.tar.xz
          sudo mv llvm-mingw-20240606-ucrt-macos-universal /opt/llvm-mingw
          export PATH=/opt/llvm-mingw/bin:/opt/homebrew/opt/bison/bin:$PATH
          git clone https://gitlab.winehq.org/jhol/wine.git
          cd wine/
          git checkout aed38b3fea259c23738d60df67d562592d394393
          # --enable-archs=x86_64,aarch64 
          ./configure --prefix=/opt/wine --disable-tests CC=/usr/bin/clang CXX=/usr/bin/clang++
          make -j8
          ./wine
      #- name: tmate
      #  uses: mxschmitt/action-tmate@v3
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
